# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: ncu

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Clean up & Prepare
        run: |
          files="./*"
          for filepath in $files; do
            if [ -d $filepath ]; then
              echo $filepath
              cd $filepath
              check=$(grep ncu run.txt >/dev/null && echo $?)
              echo $check
              if [ "$check" = "0" ]; then
                rm -rf ncu
                mkdir ncu
                cp package.json ncu/package.json
              fi
            fi
          done
      - name: Install ncu
        run: npm i -g npm-check-updates
      - name: Install
        run: |
          files="./*"
          for filepath in $files; do
            if [ -d $filepath ]; then
              echo $filepath
              cd $filepath
              if [ $(grep ncu run.txt >/dev/null && echo $?) -eq 0 ]; then
                echo $filepath
                cd ncu
                npm install
              fi
            fi
          done
      - name: Report & Update
        run: |
          files="./*"
          for filepath in $files; do
            if [ -d $filepath ]; then
              echo $filepath
              cd $filepath
              if [ $(grep ncu run.txt >/dev/null && echo $?) -eq 0 ]; then
                echo $filepath
                cd ncu
                ncu
                ncu -u
              fi
            fi
          done
      - name: Reflect
        run: |
          files="./*"
          for filepath in $files; do
            if [ -d $filepath ]; then
              echo $filepath
              cd $filepath
              if [ $(grep ncu run.txt >/dev/null && echo $?) -eq 0 ]; then
                echo $filepath
                cd ncu
                npm install
              fi
            fi
          done
      - name: Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          git add -A
          git commit -m "Push output"
          git push
