# This is a basic workflow to help you get started with Actions

name: README.md

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: generate
        run: |
          files="./*"
          for filepath in $files; do
            if [ -d $filepath ]; then
              echo $filepath
              cd $filepath
              echo -e '# Project Settings' > README.md
              echo -e '## `package.json`' >> README.md
              if [ -e "package.json" ]; then
                echo -e '**exist** [EDIT]()' >> README.md
              else
                echo -e '**`package.json` does not exist!**\nYou need to push it into this directory!' >> README.md
              fi
              echo -e '## `run.txt`' >> README.md
              if [ -e "run.txt" ]; then
                echo -e '**exist** [EDIT]()' >> README.md
              else
                echo -e '**`run.txt` does not exist!**\nYou should push it into this directory.' >> README.md
              fi
              echo '## Generate Settings' >> README.md
              if [ $(grep npm-install run.txt >/dev/null && echo $?) = "0" ]; then
                echo ' - [x] **npm-install** -=> `npm install`  ' >> README.md
              else
                echo ' - [ ] **npm-install** -=> `npm install`  ' >> README.md
              fi
              echo 'run `npm install` to generate `package-lock.json`' >> README.md
              if [ $(grep yarn-install run.txt >/dev/null && echo $?) = "0" ]; then
                echo ' - [x] **yarn-install** -=> `yarn install`  ' >> README.md
              else
                echo ' - [ ] **yarn-install** -=> `yarn install`  ' >> README.md
              fi
              echo 'run `yarn install` to generate `yarn.lock`' >> README.md
              if [ $(grep ncu run.txt >/dev/null && echo $?) = "0" ]; then
                echo ' - [x] **ncu** -=> `npm install + ncu -u`  ' >> README.md
              else
                echo ' - [ ] **ncu** -=> `npm install + ncu -u`  ' >> README.md
              fi
              echo 'run `npm install` and `ncu -u` to update vulnerability' >> README.md
            fi
          done
      - name: Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Push output"
          git push
